application:
  version: 1.0.0
  profile: D://profile
  upload: /upload/**
mybatis-plus:
  mapper-locations: classpath*:mappers/**/*Mapper.xml
  type-aliases-package: com.light.springboot.core.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0
logging:
  level:
    com.light.springboot: debug
server:
  undertow:
    accesslog:
      dir: /data/log
      enabled: false
      pattern: access_log
      suffix: log
    max-http-post-size: 20
    io-threads: 4
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true
  port: 8082
spring:
  profiles:
    active: dev
