application:
  version: 1.0.0
  profile: D://profile
  upload: /upload/**
spring:
  redis:
    host: ubuntu.wsl
    port: 6379
    lettuce:
      pool:
        max-wait: 16
        max-active: 16
        max-idle: 16
        min-idle: 1
      shutdown-timeout: 10000ms
    database: 0
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      enabled: true
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://ubuntu.wsl:3306/jira?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: "123456" #这里要加引号，不然会提示报错
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: com.light.springboot.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.light.springboot: debug
server:
  undertow:
    accesslog:
      dir: /data/log
      enabled: false
      pattern: access_log
      suffix: log
    max-http-post-size: 20
    io-threads: 4
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true
