application:
  version: 1.0.0
  profile: D://profile
  upload: /upload/**
spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      enabled: true
  profiles:
    active: dev
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/jira?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: "009014" #这里要加引号，不然会提示报错
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: com.light.springboot
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.light.springboot: debug
